options:
  formatter: stylish
  merge-default-rules: false

rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 1
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 1

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 1
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 2

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style: 0
  clean-import-paths: 0
  empty-args: 1
  hex-length: 0
  hex-notation: 2
  indentation: 2
  leading-zero: 1
  nesting-depth: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 0
