on:
  push:
    branches:
      - "**"
      - "!production"

name: Test and Lint

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8

      - name: Cache build context
        id: cache-node
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node

      - name: Install dependencies
        run: npm install --no-audit

      - name: Run lints
        run: npm run lint
